export const barrios = [
    "Alameda del Río",
    "América",
    "Barlovento",
    "Barranquillita",
    "Barrio Abajo",
    "Bellavista",
    "Betania",
    "Boston",
    "Campo Alegre",
    "Centro",
    "Ciudad Jardín",
    "Colombia",
    "El Boliche",
    "El Castillo",
    "El Porvenir",
    "El Prado",
    "El Recreo",
    "El Rosario",
    "El Tabor",
    "Granadillo",
    "Zona Industrial Vía 40",
    "La Bendición de Dios",
    "La Campiña",
    "La Concepción",
    "La Cumbre",
    "La Felicidad",
    "La Loma",
    "Las Colinas",
    "Las Delicias",
    "Las Mercedes",
    "Los Alpes",
    "Los Jobos",
    "Los Nogales",
    "Miramar",
    "Modelo",
    "Montecristo",
    "Nuevo Horizonte",
    "Paraíso",
    "Parque Rosado",
    "San Francisco",
    "Santa Ana",
    "Villa Country",
    "Villa Tarel",
    "Villanueva",
]